version: "3.7"

services:
  proxyclient1:
    image: zippersk/ws-tunnel-proxy:client
    restart: unless-stopped
    environment:
      SERVER_ADDR: http://server.local:8087
      HOST: web1
      PORT: 80
      SUBDOMAIN: webservice1

  proxyclient2:
    image: zippersk/ws-tunnel-proxy:client
    restart: unless-stopped
    environment:
      SERVER_ADDR: http://server.local:8087
      HOST: web2
      PORT: 80
      SUBDOMAIN: webservice2

  web1:
      image: strm/helloworld-http
  web2:
      image: strm/helloworld-http